#!/usr/bin/env python3
"""Write the generated pages of Solium's documentation into docs/generated/.

    dev/docs/generate.py --solium target/debug/solium [--rev <commit>]

Every page this writes is transcribed from a source that is also what the
compositor runs, so none of them can say something the code does not:

    configuration.md  crates/solium/lua/config.lua, comments and settings
    settings.md       the same file: one row per top-level setting
    bindings.md       `solium --check`, with where each binding is made
    lua-api.md        crates/solium/lua/meta/sol.lua
    environment.md    crates/solium/environment.txt, with where each is read
    rust.md           `cargo metadata`, and each crate's own `//!` summary

It also copies the Markdown files from outside docs/ that the book carries,
and splits the README into the introduction and the install page. Nothing in
docs/generated/ is committed; dev/docs.sh runs this before `mdbook build`.

Python 3 and its standard library only, so the build container needs nothing
it does not already have.
"""

import argparse
import json
import os
import posixpath
import re
import shutil
import subprocess
import sys
import tempfile

# No __pycache__ beside the scripts: the checkout is not the place for it.
sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import links  # noqa: E402

ROOT = links.ROOT
DOCS = os.path.join(ROOT, "docs")
OUT = os.path.join(DOCS, "generated")
LUA = "crates/solium/lua"
CONFIG = f"{LUA}/config.lua"
SOL_LUA = f"{LUA}/meta/sol.lua"
ENVIRONMENT = "crates/solium/environment.txt"

HEADER = (
    "<!-- Generated by dev/docs/generate.py from {source}. "
    "Edit that, not this. -->\n\n"
)


def read(path):
    with open(os.path.join(ROOT, path), encoding="utf-8") as file:
        return file.read()


def write(book_path, text, source):
    """Write one page of the book, under docs/."""
    path = os.path.join(DOCS, book_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as file:
        file.write(HEADER.format(source=source) + text.rstrip() + "\n")


def source_link(path, line=None, rev=None):
    """A link to a line of a file on GitHub."""
    # A line only means something in one commit; a file is best read as it is now.
    ref = (rev or links.BRANCH) if line else links.BRANCH
    url = f"{links.REPOSITORY}/blob/{ref}/{path}"
    return url + (f"#L{line}" if line else "")


def first_sentence(text, limit=180):
    """The first sentence of some prose, cut at a word if it runs long."""
    text = " ".join(text.split())
    match = re.search(r"(.+?[.!?])(\s|$)", text)
    sentence = match.group(1) if match else text
    if len(sentence) > limit:
        # An aside is the natural place to stop; a word boundary otherwise.
        aside = sentence.find(" -- ")
        cut = aside if 0 < aside <= limit else sentence[:limit].rfind(" ")
        sentence = sentence[:cut].rstrip(",;:") + " …"
    return sentence


# The README and the files copied in ---------------------------------------


def copies():
    for path in links.COPIED:
        destination = os.path.join(OUT, "repo", path)
        os.makedirs(os.path.dirname(destination), exist_ok=True)
        shutil.copyfile(os.path.join(ROOT, path), destination)


def sections(markdown):
    """A Markdown file cut at its `## ` headings: [(title or None, text)]."""
    out = [(None, [])]
    fenced = False
    for line in markdown.split("\n"):
        if line.startswith("```"):
            fenced = not fenced
        if not fenced and line.startswith("## "):
            out.append((line[3:].strip(), [line]))
        else:
            out[-1][1].append(line)
    return [(title, "\n".join(lines)) for title, lines in out]


def readme():
    """The README, as the introduction and the Getting started page."""
    parts = sections(read(links.README))
    found = {title for title, _ in parts}
    missing = [title for title in links.INSTALL_SECTIONS if title not in found]
    if missing:
        sys.exit(f"generate: the README has no section called {missing}")

    introduction = "\n".join(text for title, text in parts if title not in links.INSTALL_SECTIONS)
    # Included by docs/introduction.md, so its links are written from there.
    write(
        "generated/readme/introduction.md",
        links.rewrite(introduction, links.README, links.INTRODUCTION),
        links.README,
    )

    install = "\n".join(text for title, text in parts if title in links.INSTALL_SECTIONS)
    wanted = ("The thirty-second version", "Where things live")
    first = [text for title, text in sections(read("docs/ricing.md")) if title in wanted]
    if len(first) != len(wanted):
        found = {title for title, _ in sections(read("docs/ricing.md"))}
        sys.exit(f"generate: docs/ricing.md has no section called "
                 f"{[title for title in wanted if title not in found]}")
    page = (
        "# Getting started\n\n"
        "Building Solium, running it, installing it, and a first configuration. "
        "The first three sections are the README's; the last two are the start "
        "of [Ricing Solium](../ricing.md), which goes on from there.\n\n"
        + links.rewrite(install, links.README, links.GETTING_STARTED)
        + "\n\n"
        + links.rewrite("\n\n".join(first), "docs/ricing.md", links.GETTING_STARTED)
    )
    write(links.GETTING_STARTED, page, "README.md and docs/ricing.md")


# config.lua ----------------------------------------------------------------


def comment_text(line):
    """A Lua comment line without its `--` and the one space after it."""
    text = line.strip()[2:]
    return text[1:] if text.startswith(" ") else text


def indent_of(text):
    return len(text) - len(text.lstrip(" "))


def looks_like_lua(block):
    return bool(re.search(r"[={}]|\bsol\.|\breturn\b|\bfunction\b", block))


def term_list(lines):
    """Aligned `term   description` lines as a Markdown list, or None.

    Only the simple shape: every entry starts at the block's indent, its
    description continues on more-indented lines, and nothing has columns of
    its own inside it. Anything else is kept as preformatted text by the
    caller, which is always faithful and only sometimes pretty.
    """
    base = indent_of(lines[0])
    items = []
    for line in lines:
        if not line.strip():
            continue
        indent = indent_of(line)
        body = line.strip()
        if indent == base:
            if body.startswith(("* ", "- ")):
                items.append(["", body[2:]])
                continue
            match = re.match(r"^(\S.*?)\s{2,}(\S.*)$", body)
            if not match:
                return None
            items.append([match.group(1), match.group(2)])
        elif indent > base and items and not re.search(r"\S\s{2,}\S", body):
            items[-1][1] += " " + body
        else:
            return None
    if not items:
        return None
    out = []
    for term, description in items:
        if not term:
            out.append(f"- {description}")
        elif "`" in term or " " in term and not re.match(r'^[\w."\'|=+-]+(\s*[|=,]\s*[\w."\'|=+-]+)*$', term):
            out.append(f"- **{term}**: {description}")
        else:
            out.append(f"- `{term}`: {description}")
    return "\n".join(out)


def prose(comment_lines):
    """Lua comment lines as Markdown.

    Indented four or more is an example, and becomes a code block. Indented two
    or three is an aligned list, which becomes a Markdown list when its shape is
    simple enough to read one from, and preformatted text when it is not.
    Everything else is prose, which in these files is already Markdown.
    """
    lines = [comment_text(line) for line in comment_lines]
    out = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if indent_of(line) >= 2 and line.strip():
            code = indent_of(line) >= 4
            block = []
            while index < len(lines):
                current = lines[index]
                if current.strip():
                    if indent_of(current) < 2:
                        break
                    block.append(current)
                    index += 1
                    continue
                # A blank line ends the block unless the next line carries on.
                following = next((later for later in lines[index + 1:] if later.strip()), "")
                if indent_of(following) >= (4 if code else 2):
                    block.append("")
                    index += 1
                    continue
                break
            while block and not block[-1].strip():
                block.pop()
            least = min(indent_of(each) for each in block if each.strip())
            dedented = "\n".join(each[least:] for each in block)
            listed = None if code else term_list(block)
            if listed:
                out.append("\n" + listed + "\n")
            else:
                language = "lua" if code and looks_like_lua(dedented) else "text"
                out.append(f"\n```{language}\n{dedented}\n```\n")
            continue
        # A heading would be read into a line that starts with `#`.
        out.append("\\" + line if line.startswith("#") else line)
        index += 1
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)).strip()


def depth_change(line):
    """How much a line of Lua opens or closes tables, strings and comments aside."""
    code = re.sub(r'"(\\.|[^"\\])*"', '""', line)
    code = code.split("--", 1)[0]
    return code.count("{") - code.count("}")


def chunks(body, indent):
    """A table body cut into (comment lines, code lines) at each comment.

    A blank line also ends a chunk, so settings the file keeps apart stay apart
    -- but not inside a table, whose own blank lines belong to it.
    """
    out = []
    comment, code = [], []
    depth = 0

    def flush():
        if comment or code:
            out.append((list(comment), list(code)))
        comment.clear()
        code.clear()

    for line in body:
        stripped = line.strip()
        if depth > 0:
            code.append(line)
            depth += depth_change(line)
            continue
        if not stripped:
            # A comment on its own, like "There is no dock.", ends here too.
            flush()
            continue
        if stripped.startswith("--") and indent_of(line) == indent:
            if code:
                flush()
            comment.append(line)
        else:
            code.append(line)
            depth += depth_change(line)
    flush()
    return out


def keys_of(code, indent):
    """The keys a chunk of settings sets, at this depth."""
    found = []
    for line in code:
        if indent_of(line) == indent:
            match = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=", line)
            if match:
                found.append(match.group(1))
    return found


def dedent(lines, amount):
    """Lines of a table body, moved left by the depth they sit at in the file."""
    return "\n".join(line[amount:] if line[:amount].strip() == "" else line.lstrip() for line in lines)


def parse_config():
    """config.lua as (header, [top-level entries], trailer)."""
    lines = read(CONFIG).split("\n")
    start = next(i for i, line in enumerate(lines) if line.startswith("local defaults = {"))
    end = next(i for i in range(start + 1, len(lines)) if lines[i] == "}")
    header = [line for line in lines[:start] if line.startswith("--")]
    entries = []
    for comment, code in chunks(lines[start + 1:end], 4):
        keys = keys_of(code, 4)
        if not keys:
            entries.append({"key": None, "comment": comment, "code": []})
            continue
        entries.append({"key": keys[0], "comment": comment, "code": code})
    trailer = lines[end + 1:]
    if len([entry for entry in entries if entry["key"]]) < 10:
        sys.exit("generate: found fewer than ten settings in config.lua; the parse is broken")
    return header, entries, trailer


def value_summary(code):
    """A setting's default, short enough for a table cell."""
    first = code[0].split("=", 1)[1].strip().rstrip(",")
    if len(code) == 1:
        return first
    return "{ … }"


def configuration(rev):
    header, entries, trailer = parse_config()
    out = [
        "# Configuration",
        "",
        f"This page is [`config.lua`]({source_link(CONFIG, rev=rev)}), the file "
        "that sets every default, with its comments as the text and its settings "
        "as the code. To change a setting, write only that setting in "
        "`~/.config/solium/user.lua`; [Every setting](settings.md) is the index.",
        "",
        prose(header),
        "",
    ]
    for entry in entries:
        key = entry["key"]
        if key is None:
            out += [prose(entry["comment"]), ""]
            continue
        out += [f"## `{key}` {{#{key}}}", ""]
        if entry["comment"]:
            out += [prose(entry["comment"]), ""]
        code = entry["code"]
        body = code[1:-1] if len(code) > 1 and code[0].rstrip().endswith("{") else []
        if body and any(line.strip().startswith("--") for line in body):
            for comment, sub in chunks(body, 8):
                sub_keys = keys_of(sub, 8)
                if sub_keys:
                    anchors = "".join(f'<a id="{key}.{name}"></a>' for name in sub_keys[1:])
                    title = ", ".join(f"`{key}.{name}`" for name in sub_keys)
                    out += [f"### {title} {{#{key}.{sub_keys[0]}}}", ""]
                    if anchors:
                        out += [anchors, ""]
                if comment:
                    out += [prose(comment), ""]
                if sub:
                    out += ["The default:", "", "```lua", dedent(sub, 8), "```", ""]
        else:
            anchors = "".join(f'<a id="{key}.{name}"></a>' for name in keys_of(body, 8))
            if anchors:
                out += [anchors, ""]
            out += ["The default:", "", "```lua", dedent(code, 4), "```", ""]

    out += [
        "## How `user.lua` is read {#how-user-lua-is-read}",
        "",
        "The rest of `config.lua` is the code that merges your file over the "
        "defaults above and reports what it could not have meant. Its comments "
        "are the explanation; the code is folded under each.",
        "",
    ]
    block_comment, block_code = [], []

    def flush():
        if block_comment:
            out.extend([prose(block_comment), ""])
        code = "\n".join(block_code).strip("\n")
        if code:
            out.extend(["<details><summary>The code</summary>", "", "```lua", code, "```", "", "</details>", ""])
        block_comment.clear()
        block_code.clear()

    for line in trailer:
        if line.startswith("--"):
            if block_code and any(each.strip() for each in block_code):
                flush()
            block_comment.append(line)
        else:
            block_code.append(line)
    flush()
    write("generated/reference/configuration.md", "\n".join(out), CONFIG)
    return entries


def settings(entries):
    out = [
        "# Every setting",
        "",
        "One row for each top-level setting in `config.lua`, and each links to "
        "where [the configuration reference](configuration.md) explains it. A "
        "setting is written in `~/.config/solium/user.lua`, which holds only what "
        "you change:",
        "",
        "```lua",
        "return {",
        "    gap = 4,",
        "    tiling = { split = 0.618 },",
        "}",
        "```",
        "",
        "| Setting | Default | What it is |",
        "|---|---|---|",
    ]
    for entry in entries:
        key = entry["key"]
        if key is None:
            continue
        code = entry["code"]
        default = value_summary(code)
        text = first_sentence(" ".join(comment_text(line) for line in entry["comment"]
                                       if indent_of(comment_text(line)) < 2)) if entry["comment"] else ""
        body = code[1:-1] if len(code) > 1 and code[0].rstrip().endswith("{") else []
        sub_keys = keys_of(body, 8)
        if sub_keys:
            listed = ", ".join(f"[`{name}`](configuration.md#{key}.{name})" for name in sub_keys)
            text = (text + " " if text else "") + f"Keys: {listed}."
        cell = text.replace("|", "\\|")
        out.append(f"| [`{key}`](configuration.md#{key}) | `{default}` | {cell} |")
    write("generated/reference/settings.md", "\n".join(out), CONFIG)


# Bindings ----------------------------------------------------------------------


def normalise(combo):
    """`normalise_combo` in script.rs, which is what `--check` prints."""
    modifiers, key = set(), ""
    for part in combo.split("+"):
        part = part.strip().lower()
        if part in ("ctrl", "control"):
            modifiers.add("ctrl")
        elif part in ("alt", "meta"):
            modifiers.add("alt")
        elif part == "shift":
            modifiers.add("shift")
        elif part in ("super", "logo", "win", "cmd"):
            modifiers.add("super")
        elif part:
            key = part
    return "".join(f"{name}+" for name in ("ctrl", "alt", "shift", "super") if name in modifiers) + key


def check_output(solium):
    """What `solium --check` prints for the shipped configuration alone."""
    with tempfile.TemporaryDirectory() as home:
        environment = {
            "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
            "HOME": home,
            "XDG_CONFIG_HOME": os.path.join(home, "config"),
            "XDG_STATE_HOME": os.path.join(home, "state"),
            "RUST_LOG": "error",
        }
        result = subprocess.run(
            [solium, "--check"], env=environment, capture_output=True, text=True, timeout=120
        )
    if result.returncode != 0:
        sys.exit(f"generate: `solium --check` failed:\n{result.stdout}{result.stderr}")
    combos, expected = [], None
    for line in result.stdout.splitlines():
        match = re.match(r"^\s+ok: (\d+) binding", line)
        if match:
            expected = int(match.group(1))
            continue
        if expected is not None and line.startswith("    "):
            combos.append(line.split()[0])
        elif expected is not None and not line.startswith("    "):
            break
    if expected is None or len(combos) != expected:
        sys.exit(f"generate: could not read the bindings from `solium --check`:\n{result.stdout}")
    return combos


BIND = re.compile(r'^\s*(?:sol\.)?bind\(\s*"([^"]*)"\s*(\.\.\s*[A-Za-z_]\w*\s*)?,\s*(.*)$')


def handler_text(lines, index, rest):
    """What a binding calls, when it is short enough to show."""
    call = rest.rstrip()
    if call.endswith(")") and not re.match(r"^function\s*\([^)]*\)$", call):
        call = call[:-1].strip()
        inline = re.match(r"^function\s*\([^)]*\)\s*(.*?)\s*end$", call)
        return inline.group(1) if inline else call
    if re.match(r"^function\s*\([^)]*\)\s*$", call):
        body = []
        for later in lines[index + 1:]:
            if re.match(r"^\s*end\)\s*$", later):
                break
            body.append(later.strip())
        body = [each for each in body if each and not each.startswith("--")]
        if len(body) == 1:
            return body[0]
    return None


def comment_above(lines, index):
    """The comment just above a binding, skipping the bindings grouped with it."""
    at = index - 1
    while at >= 0 and BIND.match(lines[at]):
        at -= 1
    block = []
    while at >= 0 and lines[at].strip().startswith("--"):
        block.insert(0, comment_text(lines[at]))
        at -= 1
    text = " ".join(line for line in block if line.strip() and indent_of(line) < 2)
    return first_sentence(text) if text else None


def binding_sites():
    """Every `sol.bind` in the shipped Lua: literal ones, and `"prefix" .. n`."""
    sites = []
    for name in sorted(os.listdir(os.path.join(ROOT, LUA))):
        if not name.endswith(".lua"):
            continue
        path = f"{LUA}/{name}"
        lines = read(path).split("\n")
        for index, line in enumerate(lines):
            match = BIND.match(line)
            if not match or line.lstrip().startswith("local function"):
                continue
            sites.append({
                "file": name,
                "path": path,
                "line": index + 1,
                "combo": match.group(1),
                "template": bool(match.group(2)),
                "handler": handler_text(lines, index, match.group(3)),
                "comment": comment_above(lines, index),
            })
    return sites


def module_summary(path):
    lines = read(path).split("\n")
    head = []
    for line in lines:
        if not line.startswith("--"):
            break
        if not comment_text(line).strip():
            break
        head.append(comment_text(line))
    return first_sentence(" ".join(head)) if head else ""


def bindings(solium, rev):
    combos = check_output(solium)
    sites = binding_sites()
    literal = {normalise(site["combo"]): site for site in sites if not site["template"]}
    rows = {}
    unmatched = []
    for combo in combos:
        site = literal.get(combo)
        shown = site["combo"] if site else None
        if site is None:
            key = combo.split("+")[-1]
            for candidate in sites:
                if candidate["template"] and normalise(candidate["combo"] + key) == combo:
                    site, shown = candidate, candidate["combo"] + key
                    break
        if site is None:
            unmatched.append(combo)
            continue
        rows.setdefault((site["path"], site["line"]), (site, []))[1].append(shown)

    out = [
        "# Key bindings",
        "",
        f"The {len(combos)} bindings the shipped configuration makes, as "
        "`solium --check` lists them, with where each is made and what it calls. "
        "None of them belongs to the compositor: each is a `sol.bind` call in a "
        "script, so any of them can be changed or removed from the `bindings` "
        "section of `user.lua` ([how](configuration.md#bindings)), and "
        "`solium --check` then lists what your configuration replaced or removed.",
        "",
        "Two chords are the compositor's own and are not listed: `ctrl+alt+backspace` "
        "ends the session whatever the configuration says, except while the screen "
        "is locked, and `ctrl+alt+F1` to `ctrl+alt+F12` switch virtual terminal.",
        "",
        "Nor is a key a mode binds only while it is up, because `solium --check` "
        "lists what the configuration binds as it loads: `escape` leaves the "
        "overview, and is bound only while the overview is open, so that the rest "
        "of the time it reaches the application with the keyboard.",
        "",
    ]
    by_file = {}
    for (path, line), (site, shown) in sorted(rows.items(), key=lambda item: (item[0][0] != f"{LUA}/init.lua", item[0])):
        by_file.setdefault(path, []).append((site, shown))
    for path, entries in by_file.items():
        name = posixpath.basename(path)
        out += [f"## {name}", ""]
        summary = module_summary(path)
        if summary:
            out += [summary, ""]
        out += ["| Keys | What it does | Where |", "|---|---|---|"]
        for site, shown in entries:
            if len(shown) > 2:
                keys = f"`{shown[0]}` … `{shown[-1]}`"
            else:
                keys = ", ".join(f"`{combo}`" for combo in shown)
            what = []
            if site["handler"]:
                what.append(f"`{site['handler']}`")
            if site["comment"]:
                what.append(site["comment"])
            cell = " — ".join(what).replace("|", "\\|")
            where = f"[{name}:{site['line']}]({source_link(path, site['line'], rev)})"
            out.append(f"| {keys} | {cell} | {where} |")
        out.append("")
    if unmatched:
        out += ["## Made elsewhere", "",
                "Bound, but not by a `sol.bind` call this page could find:", ""]
        out += [f"- `{combo}`" for combo in unmatched]
    write("generated/reference/bindings.md", "\n".join(out), "`solium --check` and crates/solium/lua")


# sol.lua -----------------------------------------------------------------------


def parse_sol():
    """sol.lua as declarations, each with its `---` block."""
    lines = read(SOL_LUA).split("\n")
    header = []
    for line in lines[1:]:
        if line.startswith("---"):
            break
        if line.startswith("--"):
            header.append(line)
        elif header and not line.strip():
            break
    items, doc = [], []
    for number, line in enumerate(lines, 1):
        if line.startswith("---@meta"):
            continue
        if line.startswith("---"):
            doc.append(line[3:])
            continue
        if not doc:
            continue
        block, doc = doc, []
        item = {"doc": block, "line": number}
        function = re.match(r"^function ([\w.:]+)\((.*)\)", line)
        field = re.match(r"^(sol\.\w+) = ", line)
        tags = [each for each in block if each.startswith("@")]
        if function:
            item.update(kind="function", name=function.group(1),
                        params=[p.strip() for p in function.group(2).split(",") if p.strip()])
        elif field:
            item.update(kind="field", name=field.group(1))
        elif any(tag.startswith("@class") for tag in tags):
            name = next(tag.split()[1] for tag in tags if tag.startswith("@class"))
            item.update(kind="class", name=name.rstrip(":"))
        elif any(tag.startswith("@alias") for tag in tags):
            name = next(tag.split()[1] for tag in tags if tag.startswith("@alias"))
            item.update(kind="alias", name=name)
        else:
            continue
        items.append(item)
    return header, items


def description(block):
    """The prose of a `---` block: every line that is not a tag."""
    text, lines = [], []
    for line in block:
        if line.startswith("@") or line.startswith("|"):
            if lines:
                text.append(" ".join(lines))
                lines = []
            continue
        if line.strip():
            lines.append(line.strip())
        elif lines:
            text.append(" ".join(lines))
            lines = []
    if lines:
        text.append(" ".join(lines))
    return "\n\n".join(text)


def type_link(kinds, text):
    """A LuaLS type, in code, with the classes and aliases it names linked."""
    parts = re.split(r"(sol\.[A-Z]\w*|\bTree\b|\bScroller\b)", text)
    out = []
    for index, part in enumerate(parts):
        if not part:
            continue
        name = {"Tree": "sol.Tree", "Scroller": "sol.Scroller"}.get(part, part)
        if index % 2 and name in kinds:
            out.append(f"[`{part}`](#{kinds[name]})")
        else:
            out.append(f"`{part}`" if part.strip() else part)
    return "".join(out)


def tag_parts(tag):
    """`@param name type description` as (name, type, description).

    The type ends at the first space that is not inside braces, brackets or
    parentheses, which is enough for every type this file writes.
    """
    rest = tag.split(None, 1)[1] if " " in tag else ""
    if tag.startswith(("@param", "@field")):
        name, _, rest = rest.partition(" ")
    else:
        name = ""
    depth, end = 0, len(rest)
    for index, char in enumerate(rest):
        if char in "({[<":
            depth += 1
        elif char in ")}]>":
            depth -= 1
        elif char == " " and depth == 0 and not rest[:index].endswith((",", ":", "|")) \
                and not rest[index + 1:index + 2] in ("|",):
            end = index
            break
    return name, rest[:end].strip(), rest[end:].strip()


def overload_line(kinds, name, overload):
    """`fun(a: T): R`, written as the call it describes."""
    if not overload.startswith("fun("):
        return type_link(kinds, overload)
    depth = 0
    for index, char in enumerate(overload[3:], 3):
        depth += {"(": 1, ")": -1}.get(char, 0)
        if depth == 0:
            break
    arguments = overload[4:index]
    result = overload[index + 1:].lstrip(":").strip()
    line = f"`{name}({arguments})`"
    return line + (f" returns {type_link(kinds, result)}" if result else "")


def lua_api(rev):
    header, items = parse_sol()
    kinds = {}
    for item in items:
        if item["kind"] in ("class", "alias"):
            kinds[item["name"]] = "type-" + item["name"].replace(".", "-").lower()
    # A tree and a strip have sections of their own, which is where they link.
    kinds["sol.Tree"] = "tree"
    kinds["sol.Scroller"] = "scroller"
    kinds["sol.Event"] = "events"

    def function_entry(item):
        tags = [each for each in item["doc"] if each.startswith("@")]
        params = {name.rstrip("?"): (kind + ("?" if name.endswith("?") else ""), text)
                  for name, kind, text in (tag_parts(tag) for tag in tags if tag.startswith("@param"))}
        returns = [tag_parts(tag) for tag in tags if tag.startswith("@return")]
        overloads = [tag.split(None, 1)[1] for tag in tags if tag.startswith("@overload")]
        name = item["name"]
        signature = f"{name}({', '.join(item['params'])})"
        anchor = name.replace(".", "-").replace(":", "-").lower()
        out = [f"### `{signature}` {{#{anchor}}}", ""]
        text = description(item["doc"])
        if text:
            out += [text, ""]
        if overloads:
            out += ["Also called as:", ""]
            short = name.split(":")[-1] if ":" in name else name
            out += [f"- {overload_line(kinds, short, overload)}" for overload in overloads]
            out.append("")
        if item["params"]:
            out += ["Parameters:", ""]
            for param in item["params"]:
                kind, text = params.get(param, ("", ""))
                optional = kind.endswith("?") or param.endswith("?")
                line = f"- `{param}`" + (f": {type_link(kinds, kind.rstrip('?'))}" if kind else "")
                if optional:
                    line += " (optional)"
                if text:
                    line += f" — {text}"
                out.append(line)
            out.append("")
        shown = [(kind, text) for _, kind, text in returns if kind and kind != "nil"]
        if shown:
            out += ["Returns " + "; ".join(
                type_link(kinds, kind) + (f" ({text})" if text else "") for kind, text in shown) + ".", ""]
        out.append(f"<small>[sol.lua:{item['line']}]({source_link(SOL_LUA, item['line'], rev)})</small>")
        out.append("")
        return out

    def type_entry(item):
        tags = [each for each in item["doc"] if each.startswith("@")]
        name = item["name"]
        out = [f"### `{name}` {{#{kinds[name]}}}", ""]
        text = description(item["doc"])
        if text:
            out += [text, ""]
        head = next((tag for tag in tags if tag.startswith("@class")), "")
        if ":" in head:
            parent = head.split(":", 1)[1].strip()
            out += [f"Has every field of {type_link(kinds, parent)}, and:", ""]
        fields = [tag_parts(tag) for tag in tags if tag.startswith("@field")]
        for field, kind, text in fields:
            optional = field.endswith("?")
            line = f"- `{field.rstrip('?')}`: {type_link(kinds, kind)}"
            if optional:
                line += " (optional)"
            if text:
                line += f" — {text}"
            out.append(line)
        values = [line for line in item["doc"] if line.startswith("|")]
        for value in values:
            value = value[1:].strip()
            shown, _, text = value.partition(" # ")
            out.append(f"- {type_link(kinds, shown.strip())}" + (f" — {text.strip()}" if text else ""))
        if fields or values:
            out.append("")
        return out

    functions = [item for item in items if item["kind"] == "function"]
    fields = [item for item in items if item["kind"] == "field"]
    public_fields = [item for item in fields if not item["name"].startswith("sol._") and item["name"] != "sol.layout"]
    private = [item for item in fields if item["name"].startswith("sol._")]
    types = [item for item in items if item["kind"] in ("class", "alias")
             and item["name"] not in ("sol", "sol.layout", "sol.Event")]
    events = next(item for item in items if item["name"] == "sol.Event")

    count = len(functions) + len(fields)
    out = [
        "# The Lua API",
        "",
        "Everything the compositor puts in the `sol` table, transcribed from "
        f"[`sol.lua`]({source_link(SOL_LUA)}), the definitions file "
        "lua-language-server reads for completion ([how to set it up](../../ricing.md#editor-completion)). "
        f"A test fails when the compositor and that file disagree about any of its {count} names.",
        "",
        "Most calls queue a command and return nothing. The commands a handler "
        "queues are applied together when it returns, in the order it queued "
        "them, and every animated one uses the timing `sol.animate` last set in "
        "that handler. [Desktop modes](../../modes.md) is the guide to using them.",
        "",
        "## Events {#events}",
        "",
        description(events["doc"]) or "What `sol.on` can listen for.",
        "",
        "| Event | Handler arguments and meaning |",
        "|---|---|",
    ]
    for value in (line for line in events["doc"] if line.startswith("|")):
        shown, _, text = value[1:].strip().partition(" # ")
        out.append(f"| `{shown.strip().strip(chr(34))}` | {text.strip().replace('|', chr(92) + '|')} |")
    out += ["", "## `sol` {#sol}", ""]
    for item in functions:
        if item["name"].startswith("sol.") and not item["name"].startswith("sol.layout."):
            out += function_entry(item)
    for item in public_fields:
        anchor = item["name"].replace(".", "-").lower()
        out += [f"### `{item['name']}` {{#{anchor}}}", "", description(item["doc"]), ""]
    out += ["## `sol.layout` {#sol-layout}", "",
            description(next(item for item in items if item["name"] == "sol.layout")["doc"]), ""]
    for item in functions:
        if item["name"].startswith("sol.layout."):
            out += function_entry(item)
    for prefix, title, anchor, cls in (("Tree:", "A dwindle tree", "tree", "sol.Tree"),
                                       ("Scroller:", "A scrolling strip", "scroller", "sol.Scroller")):
        out += [f"## {title} {{#{anchor}}}", ""]
        doc = next(item for item in items if item["name"] == cls)
        out += [description(doc["doc"]), ""]
        for item in functions:
            if item["name"].startswith(prefix):
                out += function_entry(item)
    out += ["## Types {#types}", "",
            "The shapes of the tables the calls above take and return.", ""]
    for item in types:
        if item["name"] in ("sol.Tree", "sol.Scroller"):
            continue
        out += type_entry(item)
    out += ["## Internal {#internal}", "",
            "Tables the compositor keeps in `sol` for its own use. They are listed "
            "so the list is complete; a script should use the functions named.", ""]
    for item in private:
        out += [f"- `{item['name']}` — {description(item['doc'])}"]
    text = "\n".join(out)
    write("generated/reference/lua-api.md", text, SOL_LUA)
    return count


# Flags and environment -----------------------------------------------------------


# The Rust items a `#[cfg(test)]` can take away. See `production` in
# crates/solium/src/script/reference.rs, which this matches line for line.
TEST_ITEMS = ("mod ", "fn ", "const ", "static ", "impl", "use ", "struct ", "enum ",
              "trait ", "type ", "thread_local!", "macro_rules!")


def production(path, text):
    """A source file with every line that is not production code blanked.

    Comment lines go, and in Rust every item under `#[cfg(test)]`, so a flag a
    test hands to the test runner is not cited as a place Solium reads it. The
    same cut the environment test makes.
    """
    rust = path.endswith(".rs")
    comment = "--" if path.endswith(".lua") else "//"
    lines = text.split("\n")
    kept = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if rust and line.strip() == "#[cfg(test)]":
            indent = line[:len(line) - len(line.lstrip())]
            item = index + 1
            while item < len(lines) and lines[item].lstrip().startswith("#["):
                item += 1
            head = lines[item].strip() if item < len(lines) else ""
            head = re.sub(r"^pub(\((crate|super)\))? ", "", head)
            if head.startswith(TEST_ITEMS):
                end = item
                while end < len(lines):
                    each = lines[end]
                    rest = each[len(indent):] if each.startswith(indent) else None
                    closes = (rest is not None and not rest[:1].isspace()
                              and rest.rstrip() in ("}", "};", "];", ");"))
                    first = each.rstrip()
                    # `mod tests;`, or `fn helper() {}` with its braces closed
                    # on the same line.
                    one_line = end == item and (first.endswith(";") or (
                        "{" in first and first.count("{") == first.count("}")))
                    if closes or one_line:
                        break
                    end += 1
                end = min(end, len(lines) - 1)
                kept.extend([""] * (end + 1 - index))
                index = end + 1
                continue
        kept.append("" if line.lstrip().startswith(comment) else line)
        index += 1
    return "\n".join(kept)


# Not a name a match arm answers (`=> "SOLIUM_QML"`): that labels a log line.
VARIABLE = re.compile(r'(?<!=> )"((?:SOLIUM_|XDG_|XCURSOR_)[A-Z0-9_]+|WAYLAND_DISPLAY|DISPLAY)"')
# A flag is read where it is compared: `== "--x"`, `Some("--x")`,
# `strip_prefix("--x")`, a match arm `"--x" =>`, or `const X: &str = "--x"`.
FLAG = re.compile(r'(?:==|!=|Some\(|strip_prefix\(|starts_with\(|&str =)\s*"(--[a-z][a-z-]*)"'
                  r'|"(--[a-z][a-z-]*)"(?=\s*(?:=>|\|))')


def reads():
    """Where production code reads each `"SOLIUM_..."`, `"--flag"` and named variable."""
    found = {}
    for part in ("src", "lua", "qml"):
        for directory, _, files in os.walk(os.path.join(ROOT, "crates/solium", part)):
            for name in sorted(files):
                if not name.endswith((".rs", ".lua", ".cpp", ".h", ".qml")):
                    continue
                full = os.path.join(directory, name)
                relative = os.path.relpath(full, ROOT)
                # The environment test's own file: its strings are the names it looks for.
                if relative == "crates/solium/src/script/reference.rs":
                    continue
                with open(full, encoding="utf-8") as file:
                    text = production(relative, file.read())
                matches = [(m.start(1), m.group(1)) for m in VARIABLE.finditer(text)]
                if relative.endswith(".rs"):
                    matches += [(m.start(1) if m.group(1) else m.start(2), m.group(1) or m.group(2))
                                for m in FLAG.finditer(text)]
                for at, found_name in sorted(matches):
                    found.setdefault(found_name, []).append((relative, text.count("\n", 0, at) + 1))
    return found


def environment(rev):
    lines = read(ENVIRONMENT).split("\n")
    where = reads()
    out = [
        "# Flags and environment",
        "",
        "Every command-line flag and `SOLIUM_*` variable the compositor reads, "
        f"from [`environment.txt`]({source_link(ENVIRONMENT, rev=rev)}), with "
        "where the code reads each one. A test fails when the code reads one "
        "this page does not list.",
        "",
    ]
    entry = None
    description_lines = []

    def flush():
        nonlocal entry
        if entry is None:
            return
        name, spelled = entry
        text = links.rewrite("\n".join(description_lines).strip(), ENVIRONMENT,
                             "generated/reference/environment.md")
        out.append(f"### `{spelled}` {{#{name.lstrip('-').lower().replace('_', '-')}}}")
        out.append("")
        out.append(text)
        sites = where.get(name, [])
        if sites:
            shown = ", ".join(f"[{posixpath.basename(path)}:{line}]({source_link(path, line, rev)})"
                              for path, line in sites[:6])
            more = f" and {len(sites) - 6} more" if len(sites) > 6 else ""
            out.extend(["", f"<small>Read at {shown}{more}.</small>"])
        out.append("")
        entry = None
        description_lines.clear()

    for line in lines:
        if line.startswith("#") and not line.startswith("## "):
            continue
        if line.startswith("## "):
            flush()
            out += [line, ""]
            continue
        if line.startswith("    "):
            description_lines.append(line[4:])
            continue
        if not line.strip():
            if entry is None:
                out.append("")
            else:
                description_lines.append("")
            continue
        match = re.match(r"^((?:--[a-z][a-z-]*)|(?:[A-Z][A-Z0-9_]*))(?=$|[ =])", line)
        if match and (match.group(1).startswith("--") or match.group(1).isupper()) and len(match.group(1)) > 2:
            flush()
            entry = (match.group(1), line.strip())
            continue
        flush()
        out.append(links.rewrite(line, ENVIRONMENT, "generated/reference/environment.md"))
    flush()
    write("generated/reference/environment.md", re.sub(r"\n{3,}", "\n\n", "\n".join(out)), ENVIRONMENT)


# Rust ----------------------------------------------------------------------------


def crate_summary(path):
    """The first paragraph of a crate root's `//!` documentation."""
    lines = read(path).split("\n")
    text = []
    for line in lines:
        if line.startswith("#!["):
            continue
        if not line.startswith("//!"):
            if text:
                break
            continue
        body = line[3:].strip()
        if not body:
            if text:
                break
            continue
        text.append(body)
    return " ".join(text)


def rust():
    metadata = json.loads(subprocess.run(
        ["cargo", "metadata", "--no-deps", "--format-version", "1"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout)
    out = [
        "# Rust internals",
        "",
        "The Rust source's own documentation, built by `cargo doc --no-deps "
        "--document-private-items`, so private items are included: this is for "
        "working on Solium, not for linking against it. Each summary is the "
        "first paragraph of that crate's own documentation.",
        "",
        "| Crate | Kind | What it is |",
        "|---|---|---|",
    ]
    rows = []
    for package in metadata["packages"]:
        for target in package["targets"]:
            kinds = set(target["kind"])
            library = bool(kinds & {"lib", "rlib", "dylib", "cdylib", "staticlib", "proc-macro"})
            if not library and "bin" not in kinds:
                continue
            name = target["name"].replace("-", "_")
            source = os.path.relpath(target["src_path"], ROOT)
            kind = "library" if library else "program"
            rows.append((package["name"], name, kind, crate_summary(source)))
    for package, name, kind, summary in sorted(rows, key=lambda row: (row[0] != "solium", row[0], row[2], row[1])):
        label = name if name == package.replace("-", "_") else f"{package}: {name}"
        out.append(f"| [`{label}`](../../api/{name}/index.html) | {kind} | {summary.replace('|', chr(92) + '|')} |")
    out += [
        "",
        "[Architecture](../../architecture.md) is the design these implement, and "
        "[Contributing](../repo/CONTRIBUTING.md) how to change them.",
    ]
    write("generated/reference/rust.md", "\n".join(out), "cargo metadata and each crate's //! documentation")
    return [row[1] for row in rows]


def unlisted_docs(candidates=None):
    """Every doc under docs/ that SUMMARY.md does not link.

    mdBook renders only what SUMMARY.md lists, so a doc left out of it is left
    out of the site without a word, and the link check notices only if another
    page happens to link to it.

    `candidates` are the docs git would commit, as paths from the repository
    root, when the caller could ask git (dev/docs.sh does): a doc the checkout
    ignores, such as private notes, is not the site's business. Without them,
    every Markdown file under docs/, which in a clean checkout is the same.
    """
    summary = read("docs/SUMMARY.md")
    listed = {posixpath.normpath(target.split("#")[0])
              for target in re.findall(r"\]\(([^)\s]+\.md)(?:#[^)]*)?\)", summary)}
    if candidates is None:
        candidates = []
        for directory, subdirectories, files in os.walk(DOCS):
            if os.path.abspath(directory) == os.path.abspath(DOCS):
                subdirectories[:] = [name for name in subdirectories if name != "generated"]
            candidates += [os.path.relpath(os.path.join(directory, name), ROOT).replace(os.sep, "/")
                           for name in files if name.endswith(".md")]
    missing = []
    for candidate in candidates:
        path = posixpath.normpath(candidate)
        if not path.startswith("docs/") or not path.endswith(".md"):
            continue
        path = path[len("docs/"):]
        # Fine: the contents itself, the generated pages, a listed doc, and one
        # deleted but still in git's index.
        if (path == "SUMMARY.md" or path.startswith("generated/") or path in listed
                or not os.path.isfile(os.path.join(DOCS, path))):
            continue
        missing.append(f"docs/{path}")
    return sorted(missing)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--solium", required=True, help="the built compositor, for `--check`")
    parser.add_argument("--rev", help="the commit that line links point at; the current one by default")
    parser.add_argument("--docs-list", metavar="FILE",
                        help="the docs under docs/ that git would commit, one path from the "
                             "repository root per line, `-` for standard input; SUMMARY.md has to "
                             "list each. Every Markdown file under docs/ when not given")
    arguments = parser.parse_args()

    candidates = None
    if arguments.docs_list:
        if arguments.docs_list == "-":
            candidates = sys.stdin.read().split("\n")
        else:
            with open(arguments.docs_list, encoding="utf-8") as file:
                candidates = file.read().split("\n")
        candidates = [line.strip() for line in candidates if line.strip()]

    rev = arguments.rev
    if not rev:
        try:
            rev = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True,
                                 text=True, check=True).stdout.strip()
        except (OSError, subprocess.CalledProcessError):
            rev = links.BRANCH
            print(f"generate: warning: no --rev and no git to ask, so line links point at "
                  f"`{rev}`, where the lines they cite will move", file=sys.stderr)

    unlisted = unlisted_docs(candidates)
    if unlisted:
        which = ("git tracks these, or would add them" if candidates is not None
                 else "without a list from git, every Markdown file in docs/ counts")
        sys.exit(f"generate: docs/SUMMARY.md does not list {', '.join(unlisted)} ({which}), "
                 "so the site would leave them out. List a doc for the site in "
                 "docs/SUMMARY.md; keep one that is not out of docs/, or ignored by git")

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)
    copies()
    readme()
    entries = configuration(rev)
    settings(entries)
    bindings(arguments.solium, rev)
    names = lua_api(rev)
    environment(rev)
    crates = rust()
    print(f"generated: {len([e for e in entries if e['key']])} settings, {names} sol names, "
          f"{len(crates)} crates, {len(links.COPIED)} copied files")


if __name__ == "__main__":
    main()
